saveExact: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080 # 7 days
minimumReleaseAge: 10080
blockExoticSubdeps: true
trustLockfile: true

onlyBuiltDependencies:
  - lefthook

catalog:
  "@biomejs/biome": 2.5.12
  "@commitlint/cli": 21.2.2
  "@commitlint/config-conventional": 21.2.2
  bumpp: 12.3.0
  lefthook: 2.1.12
  taze: 21.1.0

allowBuilds:
  lefthook: true

minimumReleaseAgeExclude:
  - "@biomejs/biome@2.5.4 || 2.5.10"
  - "@biomejs/cli-darwin-arm64@2.5.4 || 2.5.10"
  - "@biomejs/cli-darwin-x64@2.5.4 || 2.5.10"
  - "@biomejs/cli-linux-arm64-musl@2.5.4 || 2.5.10"
  - "@biomejs/cli-linux-arm64@2.5.4 || 2.5.10"
  - "@biomejs/cli-linux-x64-musl@2.5.4 || 2.5.10"
  - "@biomejs/cli-linux-x64@2.5.4 || 2.5.10"
  - "@biomejs/cli-win32-arm64@2.5.4 || 2.5.10"
  - "@biomejs/cli-win32-x64@2.5.4 || 2.5.10"
