saveExact: true
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080 # 7 days
minimumReleaseAge: 10080
blockExoticSubdeps: true
trustLockfile: true

onlyBuiltDependencies:
  - lefthook

catalog:
  "@biomejs/biome": 2.5.1
  "@commitlint/cli": 21.1.0
  "@commitlint/config-conventional": 21.1.0
  bumpp: 11.1.0
  lefthook: 2.1.9
  taze: 19.14.1

allowBuilds:
  lefthook: true

minimumReleaseAgeExclude:
  - '@biomejs/biome@2.5.0'
  - '@biomejs/cli-darwin-arm64@2.5.0'
  - '@biomejs/cli-darwin-x64@2.5.0'
  - '@biomejs/cli-linux-arm64-musl@2.5.0'
  - '@biomejs/cli-linux-arm64@2.5.0'
  - '@biomejs/cli-linux-x64-musl@2.5.0'
  - '@biomejs/cli-linux-x64@2.5.0'
  - '@biomejs/cli-win32-arm64@2.5.0'
  - '@biomejs/cli-win32-x64@2.5.0'
