onlyBuiltDependencies:
  - lefthook

catalog:
  "@biomejs/biome": "2.3.4"
  "@commitlint/cli": "20.1.0"
  "@commitlint/config-conventional": "20.0.0"
  "@nivalis/biome-config": "2.3.3"
  "lefthook": "2.0.2"
